version: '3.7'


services:

# ===========================
# ======= Nats Server =======
# ===========================

  # Configuratio by nats server
  nats-server:
    image: nats:latest


# ============================
# ====== Client Gateway ======
# ============================

  # Configuration by client-gateway 
  client-gateway:
    # Directory project, requiered dockerfile
    build: 
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: client-gateway-prod
    ports:
    # Read port from file .env
      - "${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}"
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      # Replace localhost by name of server nats-server
      - NATS_SERVERS=nats://nats-server:4222
    depends_on:
      - nats-server     


# ===========================
# ==== Auth Microservice ====
# ===========================

  # Configuration by auth-ms
  auth-ms:
    # Directory project, requiered dockerfile
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: auth-ms-prod
    #restart: always
    environment:
      - PORT=${PORT_AUTH_MS}
      # Replace localhost by name of server nats-server
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    # Dependencies another projects
    depends_on:
      - nats-server      


# ===============================
# ==== Products Microservice ====
# ===============================

  # Configuration by products-ms
  products-ms:
    # Directory project, requiered dockerfile
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: products-ms-prod
    environment:
      - PORT=3001
      # Replace localhost by name of server nats-server
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db
    depends_on:
      - nats-server


# ============================
# ==== Order Microservice ====
# ============================

  # Configuration by orders-ms 
  orders-ms:
    # Directory project, requiered dockerfile
    build:
      context: ./orders-ms
      dockerfile: dockerfile.prod
      # Se envia al docker file como argumento
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    image: orders-ms-prod
    environment:
      - PORT=3002
      # Replace localhost by name of server nats-server
      - NATS_SERVERS=nats://nats-server:4222
      # Replace @ localhost by name of server orders-db
      - DATABASE_URL=${ORDERS_DATABASE_URL}
    # Dependencies another projects
    depends_on:
      - nats-server

# ===============================
# ==== Payments Microservice ====
# ===============================

  # Configuration by payments-ms
  payments-ms:
    # Directory project, requiered dockerfile
    build: 
      context: ./payments-ms
      dockerfile: dockerfile.prod
    image: payments-ms-prod
    ports:
      # Port for call endpoint
      - "${PORT_PAYMENTS_MS}:${PORT_PAYMENTS_MS}" 
    #restart: always
    environment:
      - PORT=${PORT_PAYMENTS_MS}
      # Replace localhost by name of server nats-server
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
    # Dependencies another projects
    depends_on:
      - nats-server